{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "22aea26b-c17a-43c4-ad53-b1cfcb0672f3",
   "metadata": {},
   "outputs": [],
   "source": [
    "from flask import Flask, request, jsonify\n",
    "import pandas as pd\n",
    "import glob\n",
    "from openpyxl import load_workbook\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "@app.route('/tvsummary', methods=['POST'])\n",
    "def generate_summary():\n",
    "    try:\n",
    "        # === FILE SELECTION ===\n",
    "        main_file = glob.glob(\"*ESNs & TVs.xlsx\")[0]\n",
    "        rr_file = glob.glob(\"*SAESL Data 2025.xlsx\")[0]\n",
    "        output_file = \"TV_Performance_Summary_Output.xlsx\"\n",
    "\n",
    "        # === LOAD DATA ===\n",
    "        df = pd.read_excel(main_file, sheet_name=\"TV\")\n",
    "        esn_df = pd.read_excel(main_file, sheet_name=\"ESN\", usecols=\"B:E\")\n",
    "\n",
    "        def clean_esn(val):\n",
    "            val = str(val).strip().replace(\"\\n\", \"\").replace(\"\\r\", \"\").replace(\"\\xa0\", \"\").replace(\" \", \"\")\n",
    "            if val.replace('.', '', 1).isdigit():\n",
    "                val = str(int(float(val)))\n",
    "            return val\n",
    "\n",
    "        df[\"Engine Number (Ex)\"] = df[\"Engine Number (Ex)\"].map(clean_esn)\n",
    "        current_week_esns = pd.concat([esn_df[col] for col in esn_df.columns]).dropna().map(clean_esn).unique()\n",
    "        df_current_week = df[df[\"Engine Number (Ex)\"].isin(current_week_esns)].copy()\n",
    "\n",
    "        # === DELIVERY TYPE LOGIC ===\n",
    "        def classify_delivery_type(row):\n",
    "            status = str(row[\"SAESL Status\"]).strip()\n",
    "            gate = row.get(\"Gate\", None)\n",
    "            tvr_gate = str(row.get(\"TVR Gate Raised\", \"\")).strip().upper()\n",
    "\n",
    "            if pd.isna(status) or pd.isna(gate):\n",
    "                return \"Undelivered\"\n",
    "\n",
    "            try:\n",
    "                gate = int(gate)\n",
    "            except:\n",
    "                return \"Undelivered\"\n",
    "\n",
    "            if gate == 1 and status == \"Under Review (approved TV)\":\n",
    "                return \"TV Delivered\"\n",
    "            if gate == 1:\n",
    "                if tvr_gate == \"0\":\n",
    "                    return \"Undelivered\"\n",
    "                if tvr_gate == \"1\" and status == \"Under Review (approved TV)\":\n",
    "                    return \"TV Delivered\"\n",
    "            if gate == 1 and status == \"Cleared\" and tvr_gate == \"G0\":\n",
    "                return \"TV Delivered\"\n",
    "            if gate == 2 and status == \"Cleared\" and tvr_gate in [\"G0\", \"G1\"]:\n",
    "                return \"TV Delivered\"\n",
    "            if gate == 2 and status == \"Under Review (approved TV)\" and tvr_gate in [\"G0\", \"G1\"]:\n",
    "                return \"TV Delivered\"\n",
    "            if gate in [1, 2] and status in [\"Under Review (draft)\", \"Under Review (MP Release)\", \"Cleared\", \"Cleared Mitigated\"]:\n",
    "                return \"HU/Draft Delivered\"\n",
    "            if gate in [3, 4] and status in [\"Cleared\", \"Cleared Mitigated\", \"Under Review (approved TV)\"]:\n",
    "                return \"TV Delivered\"\n",
    "            if status in [\"Need HU\", \"Need Draft\", \"Draft Clarification\", \"Need Approved TV\"]:\n",
    "                return \"Undelivered\"\n",
    "            return \"Undelivered\"\n",
    "\n",
    "        df[\"Delivery Type\"] = df.apply(classify_delivery_type, axis=1)\n",
    "        df_current_week[\"ESN\"] = df_current_week[\"Engine Number (Ex)\"]\n",
    "\n",
    "        current_week_summary = pd.DataFrame({\n",
    "            \"Metric\": [\"Total ESNs in Current Week\", \"TV Delivered\", \"HU/Draft Delivered\", \"Undelivered\", \"Delivery Rate (%)\"],\n",
    "            \"Value\": [\n",
    "                len(df_current_week),\n",
    "                (df_current_week[\"Delivery Type\"] == \"TV Delivered\").sum(),\n",
    "                (df_current_week[\"Delivery Type\"] == \"HU/Draft Delivered\").sum(),\n",
    "                (df_current_week[\"Delivery Type\"] == \"Undelivered\").sum(),\n",
    "                round(df_current_week[\"Delivery Type\"].isin([\"TV Delivered\", \"HU/Draft Delivered\"]).sum() / len(df_current_week) * 100, 2)\n",
    "                if len(df_current_week) else 0\n",
    "            ]\n",
    "        })\n",
    "\n",
    "        current_week_detail = df_current_week.groupby([\"ESN\", \"Gate\"]).agg(\n",
    "            HU_Draft_Delivered=(\"Delivery Type\", lambda x: (x == \"HU/Draft Delivered\").sum()),\n",
    "            TV_Delivered=(\"Delivery Type\", lambda x: (x == \"TV Delivered\").sum()),\n",
    "            Undelivered=(\"Delivery Type\", lambda x: (x == \"Undelivered\").sum())\n",
    "        ).reset_index()\n",
    "\n",
    "        current_week_detail[\"Total Delivered\"] = current_week_detail[\"HU_Draft_Delivered\"] + current_week_detail[\"TV_Delivered\"]\n",
    "        current_week_detail[\"Total Count\"] = current_week_detail[\"Total Delivered\"] + current_week_detail[\"Undelivered\"]\n",
    "        current_week_detail[\"Delivery %\"] = round(current_week_detail[\"Total Delivered\"] / current_week_detail[\"Total Count\"] * 100, 2)\n",
    "\n",
    "        delivery_type_breakdown = df[\"Delivery Type\"].value_counts().reset_index()\n",
    "        delivery_type_breakdown.columns = [\"Delivery Type\", \"Count\"]\n",
    "\n",
    "        gate_perf_all = df.groupby(\"Gate\").agg(\n",
    "            Total_TVs=(\"Custom ID\", \"count\"),\n",
    "            Delivered=(\"Delivery Type\", lambda x: x.isin([\"TV Delivered\", \"HU/Draft Delivered\"]).sum()),\n",
    "            TV_Delivered=(\"Delivery Type\", lambda x: (x == \"TV Delivered\").sum()),\n",
    "            HU_Draft_Delivered=(\"Delivery Type\", lambda x: (x == \"HU/Draft Delivered\").sum()),\n",
    "            Undelivered=(\"Delivery Type\", lambda x: (x == \"Undelivered\").sum())\n",
    "        ).reset_index()\n",
    "        gate_perf_all[\"Delivery %\"] = round(gate_perf_all[\"Delivered\"] / gate_perf_all[\"Total_TVs\"] * 100, 2)\n",
    "\n",
    "        summary_all_df = pd.DataFrame({\n",
    "            \"Metric\": [\"Total TVs in List\", \"Total Delivered (TV or HU)\", \"TV Delivered\", \"HU/Draft Delivered\",\n",
    "                       \"Total Undelivered\", \"Delivery Rate (%)\"],\n",
    "            \"Value\": [\n",
    "                len(df),\n",
    "                df[\"Delivery Type\"].isin([\"TV Delivered\", \"HU/Draft Delivered\"]).sum(),\n",
    "                (df[\"Delivery Type\"] == \"TV Delivered\").sum(),\n",
    "                (df[\"Delivery Type\"] == \"HU/Draft Delivered\").sum(),\n",
    "                (df[\"Delivery Type\"] == \"Undelivered\").sum(),\n",
    "                round(df[\"Delivery Type\"].isin([\"TV Delivered\", \"HU/Draft Delivered\"]).sum() / len(df) * 100, 2)\n",
    "                if len(df) else 0\n",
    "            ]\n",
    "        })\n",
    "\n",
    "        # === RR Tag Discrepancy Check ===\n",
    "        wb = load_workbook(rr_file, data_only=True)\n",
    "        ws = wb[\"Export\"]\n",
    "        green_tv_nos = []\n",
    "\n",
    "        for row in ws.iter_rows(min_row=2):\n",
    "            cell = row[0]\n",
    "            fill = cell.fill\n",
    "            if fill.start_color.rgb in (\"FF92D050\"):\n",
    "                green_tv_nos.append(str(cell.value).strip())\n",
    "\n",
    "        rr_df_full = pd.read_excel(rr_file, sheet_name=\"Export\")\n",
    "        rr_df = rr_df_full[\n",
    "            (rr_df_full[\"Tag delivered?\"] == \"Yes\") &\n",
    "            (rr_df_full[\"Applicant\"].str.strip() == \"SAESL\") &\n",
    "            (rr_df_full[\"TV NO\"].astype(str).str.strip().isin(green_tv_nos))\n",
    "        ].copy()\n",
    "\n",
    "        rr_df[\"Custom ID\"] = rr_df[\"TV NO\"].astype(str).str.strip()\n",
    "        df[\"Custom ID\"] = df[\"Custom ID\"].astype(str).str.strip()\n",
    "\n",
    "        rr_df[\"Your Status\"] = rr_df[\"Custom ID\"].map(df.set_index(\"Custom ID\")[\"Delivery Type\"].to_dict()).fillna(\"Not Found\")\n",
    "        rr_discrepancies = rr_df[rr_df[\"Your Status\"] == \"Undelivered\"].copy()\n",
    "        rr_df_status_map = df.set_index(\"Custom ID\")[\"SAESL Status\"].to_dict()\n",
    "        rr_discrepancies[\"Actual SAESL Status\"] = rr_discrepancies[\"Custom ID\"].map(rr_df_status_map)\n",
    "\n",
    "        rr_discrepancies = rr_discrepancies[[\"Custom ID\", \"Gate\", \"Your Status\", \"Actual SAESL Status\", \"Tag delivered?\"]]\n",
    "        rr_discrepancies.columns = [\"TV Number\", \"Gate\", \"Your Status\", \"Actual SAESL Status\", \"RR Tag Delivered\"]\n",
    "\n",
    "        rr_tagged = rr_df.copy()\n",
    "        rr_tagged[\"Your Status\"] = rr_tagged[\"Custom ID\"].map(df.set_index(\"Custom ID\")[\"Delivery Type\"].to_dict()).fillna(\"Not Found\")\n",
    "\n",
    "        rr_gate_summary = rr_tagged.groupby(\"Gate\").agg(RR_Tagged_Delivered=(\"Custom ID\", \"count\")).reset_index()\n",
    "\n",
    "        true_status_breakdown = rr_tagged.groupby([\"Gate\", \"Your Status\"]).agg(Count=(\"Custom ID\", \"count\")).reset_index()\n",
    "        true_status_pivot = true_status_breakdown.pivot(index=\"Gate\", columns=\"Your Status\", values=\"Count\").fillna(0).reset_index()\n",
    "        true_status_pivot.columns.name = None\n",
    "\n",
    "        with pd.ExcelWriter(output_file, engine=\"openpyxl\") as writer:\n",
    "            summary_all_df.to_excel(writer, sheet_name=\"Summary (All Tags)\", index=False)\n",
    "            current_week_summary.to_excel(writer, sheet_name=\"Current Week Summary\", index=False)\n",
    "            current_week_detail.to_excel(writer, sheet_name=\"Current Week ESN Detail\", index=False)\n",
    "            delivery_type_breakdown.to_excel(writer, sheet_name=\"Delivery Breakdown\", index=False)\n",
    "            gate_perf_all.to_excel(writer, sheet_name=\"Gate Perf (All TVs)\", index=False)\n",
    "            rr_discrepancies.to_excel(writer, sheet_name=\"RR Discrepancy\", index=False)\n",
    "            rr_gate_summary.to_excel(writer, sheet_name=\"RR Gate Summary\", index=False)\n",
    "            true_status_pivot.to_excel(writer, sheet_name=\"RR True Delivery Breakdown\", index=False)\n",
    "            df.to_excel(writer, sheet_name=\"Raw Data\", index=False)\n",
    "\n",
    "        return jsonify({\"status\": \"success\", \"message\": f\"✅ Export complete: {output_file}\"}), 200\n",
    "\n",
    "    except Exception as e:\n",
    "        return jsonify({\"status\": \"error\", \"message\": str(e)}), 500\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run(host='0.0.0.0', port=10000)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
